name: 'D1'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run main' # 步骤二，执行sh命令文件
        run: npm install && npm run main # 运行目录是仓库根目录
